/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main_Package;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Rizdhan Syahlan
 */
public class login extends javax.swing.JFrame {
    mainclass mc = new mainclass(); //untuk mendeklarasikan mainclass.java 
    /**
     * Creates new form login
     */
    Color paneDefault;
    Color paneClosed;
    int x, y;
    
    public login() {
        initComponents();
        jLabel3.requestFocusInWindow(); //untuk tidak automatis nulis di user field
        lgn_pass.setEchoChar((char)0); //untuk menunjukan password field sementara
        lgn_user.setText("Username"); //untuk mengganti user field
        lgn_pass.setText("Password"); //untuk mengganti password field
        mc.l_user = "Username"; //untuk memberi nilai awal dari username
        mc.l_pass = "Password"; //untuk memberi nilai awal dari password
        
        //untuk warna icon close
        paneDefault = new Color (0, 23, 45);
        paneClosed = new Color (245, 91, 49);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lgn_user = new javax.swing.JTextField();
        lgn_pass = new javax.swing.JPasswordField();
        show = new javax.swing.JCheckBox();
        lgn_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        paneClose = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(2, 56, 110));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 23, 45), 3));

        back2.setBackground(new java.awt.Color(17, 92, 152));

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN ADMIN");

        lgn_user.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        lgn_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lgn_userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lgn_userFocusLost(evt);
            }
        });
        lgn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgn_userMouseClicked(evt);
            }
        });
        lgn_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lgn_userKeyReleased(evt);
            }
        });

        lgn_pass.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        lgn_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lgn_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lgn_passFocusLost(evt);
            }
        });
        lgn_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgn_passMouseClicked(evt);
            }
        });
        lgn_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lgn_passKeyReleased(evt);
            }
        });

        show.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("Show Password");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        lgn_btn.setBackground(new java.awt.Color(0, 38, 77));
        lgn_btn.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        lgn_btn.setForeground(new java.awt.Color(255, 255, 255));
        lgn_btn.setText("Login");
        lgn_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lgn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgn_btnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile.png"))); // NOI18N
        jLabel2.setAlignmentX(0.5F);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lock.png"))); // NOI18N

        javax.swing.GroupLayout back2Layout = new javax.swing.GroupLayout(back2);
        back2.setLayout(back2Layout);
        back2Layout.setHorizontalGroup(
            back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(back2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lgn_user))
                    .addGroup(back2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(show)
                            .addComponent(lgn_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lgn_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        back2Layout.setVerticalGroup(
            back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgn_user))
                .addGap(15, 15, 15)
                .addGroup(back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lgn_pass)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgn_btn)
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(new java.awt.Color(0, 23, 45));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        paneClose.setBackground(new java.awt.Color(0, 23, 45));
        paneClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneCloseMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_icon.png"))); // NOI18N

        javax.swing.GroupLayout paneCloseLayout = new javax.swing.GroupLayout(paneClose);
        paneClose.setLayout(paneCloseLayout);
        paneCloseLayout.setHorizontalGroup(
            paneCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCloseLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneCloseLayout.setVerticalGroup(
            paneCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jLabel5.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Perpustakaan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(paneClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lgn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgn_btnActionPerformed
        mc.loginUser();
        if(mc.getL_user().equals(mc.user) && (mc.getL_pass().equals(mc.pass))) {
            String pesan = "Selamat Datang ";
            JOptionPane.showMessageDialog(null,pesan + mc.getUser());

            main mn = new main();
            mn.setVisible(true);
            mn.l_label.setText("Selamat Datang " + mc.getUser());
        }
        else {
            String pesan = "Username & Password Salah\nHarap Masukan Ulang";
            JOptionPane.showMessageDialog(null,pesan);
            lgn_user.setText("Username");
            lgn_pass.setEchoChar((char)0);
            lgn_pass.setText("Password");
        }
    }//GEN-LAST:event_lgn_btnActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if(show.isSelected()){ 
            lgn_pass.setEchoChar((char)0);
        }else{
            if(lgn_pass.getText().equals("Password")){
                lgn_pass.setEchoChar((char)0);
            }
            else{
                lgn_pass.setEchoChar('*');
            }
        }
        // Sebuah method untuk menampilkan password ketika check box di ceklis
    }//GEN-LAST:event_showActionPerformed

    private void lgn_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lgn_passKeyReleased
        mc.setL_pass(lgn_pass.getText()); 
        //untuk memasukan nilai dari input text ke mainnclass.java
    }//GEN-LAST:event_lgn_passKeyReleased

    private void lgn_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lgn_passFocusLost
        if (lgn_pass.getText().equals("")){
            lgn_pass.setEchoChar((char)0);
            lgn_pass.setText("Password");
        }
        // Sebuah method untuk mengganti JPasswordField ketika kehilangan focus
    }//GEN-LAST:event_lgn_passFocusLost

    private void lgn_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lgn_passFocusGained
        if (mc.getL_pass().equals("Password")){
            lgn_pass.setEchoChar('*');
            lgn_pass.setText("");
        }else{
        }
        // Sebuah method untuk mengganti JPasswordField ketika mendapatkan focus
    }//GEN-LAST:event_lgn_passFocusGained

    private void lgn_userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lgn_userKeyReleased
        mc.setL_user(lgn_user.getText());
        //untuk memasukan nilai dari input text ke mainnclass.java
    }//GEN-LAST:event_lgn_userKeyReleased

    private void lgn_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lgn_userFocusLost
        if (lgn_user.getText().equals("")){
            lgn_user.setText("Username");
            // Sebuah method untuk mengganti JPasswordField ketika kehilangan focus
        }
    }//GEN-LAST:event_lgn_userFocusLost

    private void lgn_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lgn_userFocusGained
        if (mc.getL_user().equals("Username")){
            lgn_user.setText("");
        }else{
        }
        // Sebuah method untuk mengganti JPasswordField ketika mendapatkan focus
    }//GEN-LAST:event_lgn_userFocusGained

    private void paneCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCloseMouseClicked
        System.exit(0); //untuk close login
    }//GEN-LAST:event_paneCloseMouseClicked

    private void paneCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCloseMouseEntered
        paneClose.setBackground(paneClosed);
        //untuk mengganti warna panel ketika cursor berada di panelnya
    }//GEN-LAST:event_paneCloseMouseEntered

    private void paneCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCloseMouseExited
        paneClose.setBackground(paneDefault);
        //untuk mengganti warna panel ketika cursor berada di panelnya
    }//GEN-LAST:event_paneCloseMouseExited

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
        //untuk mendapatkan posisi horizontal dan vertikal dari mouse ketika di tekan tahan
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x , yy-y);
        //untuk mendapatkan posisi horizontal dan vertikal absolut dari event terhadap layar monitor
        //serta untuk mengatur lokasi dari objek tersebut berdasarkan posisi absolut dari event 
    }//GEN-LAST:event_jPanel2MouseDragged

    private void lgn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgn_userMouseClicked
        lgn_user.setText(""); //untuk mengosongkan textfield ketika di klik
    }//GEN-LAST:event_lgn_userMouseClicked

    private void lgn_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgn_passMouseClicked
        lgn_pass.setText(""); //untuk mengosongkan textfield ketika di klik
    }//GEN-LAST:event_lgn_passMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lgn_btn;
    private javax.swing.JPasswordField lgn_pass;
    private javax.swing.JTextField lgn_user;
    private javax.swing.JPanel paneClose;
    private javax.swing.JCheckBox show;
    // End of variables declaration//GEN-END:variables
}
